=== atheurer/rickshaw/util/JSON/schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "type": "object",
    "properties": {
        "schema": {
            "type": "object",
            "properties": {
                "version": {
                    "type": "string",
                    "enum": [
                        "2023.09.27"
                    ]
                }
            }
        },
        "tags": {
            "type": "object",
            "additionalProperties": {
                "type": "string"
            }
        },
        "endpoints": {
            "type": "array",
            "items": {
                "minItems": 1,
                "type": "object"
            }
        },
        "tool-params": {
            "type": "array",
            "items": {
                "minItems": 0,
                "type": "object"
            }
        },
        "run-params": {
            "type": "object",
	    "properties": {
		"num-samples": {
		    "type": "integer",
		    "minimum": 1
		},
		"max-sample-failures": {
		    "type": "integer",
		    "minimum": 1
		},
		"test-order": {
		    "type": "string",
		    "enum": [
			"s",
			"i",
			"r"
		    ]
		}
	    },
	    "additionalProperties": false,
	    "required": []
        },
        "benchmarks": {
            "type": "array",
            "minItems": 1,
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },  
                    "ids": {
			"$ref": "#/definitions/number-lists"
                    },
                    "mv-params": {
                        "anyOf": [
                            {
                                "type": "array",
                                "items": {
                                    "minItems": 1,
                                    "type": "object"
                                }
                            },
                            {
                                "type": "object"
                            }
                        ]
                    }
                },
                "additionalProperties": false,
                "required": [
                    "name",
                    "ids",
                    "mv-params"
                ]
            }
        }
    },
    "additionalProperties": false,
    "required": [
        "benchmarks"
    ],
    "definitions": {
        "number-lists": {
            "anyOf": [
                {
                    "type": "string",
                    "pattern": "^(([1-9][0-9]*)(-[1-9][0-9]*)?)(\\+(([1-9][0-9]*)(-[1-9][0-9]*)?))*$"
                },
                {
                    "type": "integer"
                },
                {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "anyOf": [
                            {
                                "type": "string",
                                "pattern": "^(([1-9][0-9]*)(-[1-9][0-9]*)?)$"
                            },
                            {
                                "type": "integer"
                            }
                        ]
                    }
                }
            ]
        }
    }
}

=== atheurer/rickshaw/util/crucible-ci/hwnoise.k8s.json
{
    "benchmarks": [
        {
            "name": "hwnoise",
            "ids": "1",
            "mv-params": {
                "global-options": [
                    {
                        "name": "common-params",
                        "params": [
			    { "arg": "duration", "vals": [ "10" ], "role": "client" },
                            { "arg": "smt", "vals": [ "off" ], "role": "client" }
                        ]
                    }
                ],
                "sets": [
                    {
                        "include": "common-params"
                    }
                ]
            }
        }
    ],
    "tool-params": [
        {
            "tool": "sysstat"
        },
        {
            "tool": "procstat"
        },
        {
            "tool": "kernel",
            "params": [
                {
                    "arg": "subtools",
                    "val": "turbostat"
                }
            ]
        }
    ],
    "tags": {
        "description": "hwnoise-k8s-run-file-json"
    },
    "endpoints": [
        {
            "type": "k8s",
            "controller-ip": "CONTROLLER_IP",
            "host": "CI_ENDPOINT_HOST",
            "user": "CI_ENDPOINT_USER",
            "client": 1,
            "config": [
                {
                    "targets": [
                        { "role": "client", "ids": "1" }
                    ],
                    "settings": {
                        "securityContext": {
                            "capabilities": {
				"privileged": true,
                                "add": [ "SYS_NICE", "IPC_LOCK" ]
                            }
                        }
                    }
                },
                {
                    "targets": "all",
                    "settings": {
                        "cpu-partitioning": 1
                    }
                }
            ]
        }
    ],
    "run-params": {
	"num-samples": 1,
	"test-order": "s"
    }
}

=== atheurer/rickshaw/util/crucible-ci/oslat.remotehosts.json
{
    "benchmarks": [
        {
            "name": "oslat",
            "ids": "1-2",
            "mv-params": {
                "global-options": [
                    {
                        "name": "common-params",
                        "params": [
                            { "arg": "duration", "vals": [ "10", "15" ], "role": "client" }
                        ]
                    }
                ],
                "sets": [
                    {
                        "include": "common-params"
                    }
                ]
            }
        }
    ],
    "tool-params": [
        {
            "tool": "sysstat"
        },
        {
            "tool": "procstat"
        }
    ],
    "tags": {
        "description": "oslat-remotehosts-run-file-json"
    },
    "endpoints": [
	{
	    "type": "remotehosts",
	    "settings": {
		"user": "CI_ENDPOINT_USER",
		"controller-ip-address": "CONTROLLER_IP",
		"cpu-partitioning": true
	    },
	    "remotes": [
		{
		    "engines": [
			{ "role": "client", "ids": [ 1 ] },
			{ "role": "server", "ids": [ 1 ] }
		    ],
		    "config": {
			"host": "CI_ENDPOINT_HOST",
			"settings": {
			    "osruntime": "podman"
			}
		    }
		},
		{
		    "engines": [
			{ "role": "client", "ids": [ 2 ] }
		    ],
		    "config": {
			"host": "CI_ENDPOINT_HOST",
			"settings": {
			    "osruntime": "chroot"
			}
		    }
		}
	    ]
	}
    ],
    "run-params": {
	"num-samples": 1,
	"test-order": "s"
    }
}

=== atheurer/rickshaw/util/crucible-ci/sleep.remotehosts.json
{
    "benchmarks": [
        {
            "name": "sleep",
            "ids": "1-2",
            "mv-params": {
                "global-options": [
                    {
			"name": "required",
			"params": [
			    { "arg": "seconds", "vals": [ "10" ] }
			]
                    }
                ],
                "sets": [
                    {
			"include": "required"
                    }
                ]
            }
        }
    ],
    "tool-params": [
        {
            "tool": "sysstat"
        },
        {
            "tool": "procstat"
        },
        {
            "tool": "kernel",
            "params": [
                {
                    "arg": "subtools",
                    "val": "turbostat"
                }
            ]
        }
    ],
    "tags": {
        "description": "sleep-remotehosts-run-file-json"
    },
    "endpoints": [
	{
	    "type": "remotehosts",
	    "settings": {
		"user": "CI_ENDPOINT_USER",
		"controller-ip-address": "CONTROLLER_IP"
	    },
	    "remotes": [
		{
		    "engines": [
			{ "role": "client", "ids": [ 1 ] }
		    ],
		    "config": {
			"host": "CI_ENDPOINT_HOST",
			"settings": {
			    "osruntime": "podman"
			}
		    }
		},
		{
		    "engines": [
			{ "role": "client", "ids": [ 2 ] }
		    ],
		    "config": {
			"host": "CI_ENDPOINT_HOST",
			"settings": {
			    "osruntime": "chroot"
			}
		    }
		}
	    ]
	}
    ],
    "run-params": {
	    "num-samples": 1,
	    "test-order": "s"
    }
}

=== atheurer/rickshaw/util/crucible-ci/cyclictest.remotehost.json
{
    "benchmarks": [
        {
            "name": "cyclictest",
            "ids": "1",
            "mv-params": {
                "global-options": [
                {
                    "name": "required",
                    "params": [
                            { "arg": "duration", "vals": [ "10" ], "role": "client" },
                        { "arg": "priority", "vals": [ "1" ], "role": "client" },
                            { "arg": "smi", "vals": [ "off" ], "role": "client" }
                    ]
                }
                ],
                "sets": [
                {
                    "include": "required"
                    }
                ]
            }
        }
    ],
    "tool-params": [
        {
            "tool": "sysstat",
            "params": [
                { "arg": "subtools", "val": "mpstat", "enabled": "yes" }
            ]
        },
        {
            "tool": "procstat"
        }
    ],
    "tags": {
        "run": "cyclictest-run-file-json",
        "userenv": "default"
    },
    "endpoints": [
        {
            "type": "remotehost",
            "controller-ip": "CONTROLLER_IP",
            "host": "CI_ENDPOINT_HOST",
            "user": "CI_ENDPOINT_USER",
            "userenv": "default",
            "server": "1",
            "client": "1-2",
            "config": [
                {
                    "targets": [
                        { "role": "client", "ids": "1" },
                        { "role": "server", "ids": "1" }
                    ],
                    "settings": {
                        "osruntime": "podman"
                    }
                },
                {
                    "targets": [
                        { "role": "client", "ids": "2" }
                    ],
                   "settings": {
                        "osruntime": "chroot"
                    }
                },
                {
                   "targets": "default",
                   "settings": {
                        "cpu-partitioning": "1"
                    }
                }             
            ]
        },
        {
            "type": "remotehost",
            "controller-ip": "CONTROLLER_IP",
            "host": "CI_ENDPOINT_HOST",
            "user": "CI_ENDPOINT_USER",
            "userenv": "default",
            "profiler": "1",
            "config": [
                {
                    "targets": [
                        { "role": "profiler", "ids": "1" }
                    ],
                    "settings": {
                        "osruntime": "chroot"
                    }
                }
            ]
        }
    ],
    "run-params": {
	    "num-samples": 1,
	    "test-order": "s"
    }
}

=== atheurer/rickshaw/util/crucible-ci/uperf.remotehost.json
{
    "benchmarks": [
        {
            "name": "uperf",
            "ids": "1-2",
            "mv-params": {
                "global-options": [
                    {
                        "name": "required",
                        "params": [
                            { "arg": "protocol", "vals": [ "tcp" ], "role": "client" },
                            { "arg": "wsize", "vals": [ "64" ], "role": "client" },
                            { "arg": "rsize", "vals": [ "64" ], "role": "client" },
                            { "arg": "duration", "vals": [ "10" ], "role": "client" },
                            { "arg": "ifname", "vals" : [ "default-route" ], "role": "server" }
                        ]
                    }
                ],
                "sets": [
                    {
                        "include": "required",
                        "params": [
                            { "arg": "test-type", "vals": [ "stream" ], "role": "client" },
                            { "arg": "nthreads", "vals": [ "1", "8" ], "role": "client" }
                        ]
                    }
                ]
            }
        }
    ],
    "tool-params": [
        {
            "tool": "sysstat"
        },
        {
            "tool": "procstat"
        },
        {
            "tool": "kernel",
            "params": [
                {
                    "arg": "subtools",
                    "val": "turbostat"
                }
            ]
        }
    ],
    "tags": {
        "description": "uperf-remotehost-run-file-json"
    },
    "endpoints": [
        {
            "type": "remotehost",
            "controller-ip": "CONTROLLER_IP",
            "host": "CI_ENDPOINT_HOST",
            "user": "CI_ENDPOINT_USER",
            "userenv": "default",
            "server": "1-2",
            "client": "1-2",
            "config": [
                {
                    "targets": [
                        { "role": "client", "ids": "1" },
                        { "role": "server", "ids": "1" }
                    ],
                    "settings": {
                        "osruntime": "podman"
                    }
                },
                {
                    "targets": [
                        { "role": "client", "ids": "2" },
                        { "role": "server", "ids": "2" }
                    ],
                   "settings": {
                        "osruntime": "chroot"
                    }
                }             
            ]
        },
        {
            "type": "remotehost",
            "controller-ip": "CONTROLLER_IP",
            "host": "CI_ENDPOINT_HOST",
            "user": "CI_ENDPOINT_USER",
            "userenv": "default",
            "profiler": "1",
            "config": [
                {
                    "targets": [
                        { "role": "profiler", "ids": "1" }
                    ],
                    "settings": {
                        "osruntime": "chroot"
                    }
                }
            ]
        }
    ],
    "run-params": {
	    "num-samples": 1,
	    "test-order": "s"
    }
}

=== atheurer/rickshaw/util/crucible-ci/iperf.kube.json
{
    "benchmarks": [
        {
            "name": "iperf",
            "ids": "1-2",
            "mv-params": {
                "global-options": [
                    {
                        "name": "required",
                        "params": [
			    { "arg": "time", "vals": [ "10" ], "role": "client" },
			    { "arg": "protocol", "vals": [ "tcp" ] },
			    { "arg": "bitrate", "vals": [ "0" ] },
			    { "arg": "ifname", "vals" : [ "default-route" ], "role": "server" }
                        ]
                    }
                ],
                "sets": [
                    {
                        "include": "required",
                        "params": [
			    { "arg": "length", "vals": [ "256", "1024" ] }
                        ]
                    }
                ]
            }
        }
    ],
    "tool-params": [
        {
            "tool": "sysstat"
        },
        {
            "tool": "procstat"
        },
        {
            "tool": "kernel",
            "params": [
                {
                    "arg": "subtools",
                    "val": "turbostat"
                }
            ]
        }
    ],
    "tags": {
        "description": "iperf-kube-run-file-json"
    },
    "endpoints": [
	{
	    "type": "kube",
	    "controller-ip-address": "CONTROLLER_IP",
	    "host": "CI_ENDPOINT_HOST",
	    "user": "CI_ENDPOINT_USER",
	    "engines": {
		"server": "1-2",
		"client": "1-2"
	    }
	}
    ],
    "run-params": {
	    "num-samples": 1,
	    "test-order": "s"
    }
}
