=== atheurer/rickshaw/util/JSON/schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "type": "object",
    "properties": {
        "schema": {
            "type": "object",
            "properties": {
                "version": {
                    "type": "string",
                    "enum": [
                        "2023.09.27"
                    ]
                }
            }
        },
        "tags": {
            "type": "object",
            "additionalProperties": {
                "type": "string"
            }
        },
        "endpoints": {
            "type": "array",
            "items": {
                "minItems": 1,
                "type": "object"
            }
        },
        "tool-params": {
            "type": "array",
            "items": {
                "minItems": 0,
                "type": "object"
            }
        },
        "run-params": {
            "type": "object",
	    "properties": {
		"num-samples": {
		    "type": "integer",
		    "minimum": 1
		},
		"max-sample-failures": {
		    "type": "integer",
		    "minimum": 1
		},
		"test-order": {
		    "type": "string",
		    "enum": [
			"s",
			"i",
			"r"
		    ]
		}
	    },
	    "additionalProperties": false,
	    "required": []
        },
        "benchmarks": {
            "type": "array",
            "minItems": 1,
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },  
                    "ids": {
			"$ref": "#/definitions/number-lists"
                    },
                    "mv-params": {
                        "anyOf": [
                            {
                                "type": "array",
                                "items": {
                                    "minItems": 1,
                                    "type": "object"
                                }
                            },
                            {
                                "type": "object"
                            }
                        ]
                    }
                },
                "additionalProperties": false,
                "required": [
                    "name",
                    "ids",
                    "mv-params"
                ]
            }
        }
    },
    "additionalProperties": false,
    "required": [
        "benchmarks"
    ],
    "definitions": {
        "number-lists": {
            "anyOf": [
                {
                    "type": "string",
                    "pattern": "^(([1-9][0-9]*)(-[1-9][0-9]*)?)(\\+(([1-9][0-9]*)(-[1-9][0-9]*)?))*$"
                },
                {
                    "type": "integer"
                },
                {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "anyOf": [
                            {
                                "type": "string",
                                "pattern": "^(([1-9][0-9]*)(-[1-9][0-9]*)?)$"
                            },
                            {
                                "type": "integer"
                            }
                        ]
                    }
                }
            ]
        }
    }
}

=== atheurer/rickshaw/util/crucible-ci/oslat.k8s.json
{
    "benchmarks": [
        {
            "name": "oslat",
            "ids": "1",
            "mv-params": {
                "global-options": [
                    {
                        "name": "common-params",
                        "params": [
                            { "arg": "duration", "vals": [ "10", "15" ], "role": "client" }
                        ]
                    }
                ],
                "sets": [
                    {
                        "include": "common-params"
                    }
                ]
            }
        }
    ],
    "tool-params": [
        {
            "tool": "sysstat"
        },
        {
            "tool": "procstat"
        },
        {
            "tool": "kernel",
            "params": [
                {
                    "arg": "subtools",
                    "val": "turbostat"
                }
            ]
        }
    ],
    "tags": {
        "description": "oslat-k8s-run-file-json"
    },
    "endpoints": [
        {
            "type": "k8s",
            "controller-ip": "CONTROLLER_IP",
            "host": "CI_ENDPOINT_HOST",
            "user": "CI_ENDPOINT_USER",
            "server": 1,
            "client": 1,
            "config": [
                {
                    "targets": [
                        { "role": "client", "ids": "1" }
                    ],
                    "settings": {
                        "securityContext": {
                            "capabilities": {
                                "add": [ "SYS_NICE", "IPC_LOCK" ]
                            }
                        }
                    }
                },
                {
                    "targets": "all",
                    "settings": {
                        "cpu-partitioning": 1
                    }
                }
            ]
        }
    ],
    "run-params": {
	"num-samples": 1,
	"test-order": "s"
    }
}

=== atheurer/rickshaw/util/crucible-ci/iperf.remotehost.json
{
    "benchmarks": [
        {
            "name": "iperf",
            "ids": "1-2",
            "mv-params": {
                "global-options": [
                    {
                        "name": "required",
                        "params": [
			    { "arg": "time", "vals": [ "10" ], "role": "client" },
			    { "arg": "protocol", "vals": [ "tcp" ] },
			    { "arg": "bitrate", "vals": [ "0" ] },
			    { "arg": "ifname", "vals" : [ "default-route" ], "role": "server" }
                        ]
                    }
                ],
                "sets": [
                    {
                        "include": "required",
                        "params": [
			    { "arg": "length", "vals": [ "256", "1024" ] }
                        ]
                    }
                ]
            }
        }
    ],
    "tool-params": [
        {
            "tool": "sysstat"
        },
        {
            "tool": "procstat"
        }
    ],
    "tags": {
        "description": "iperf-remotehost-run-file-json"
    },
    "endpoints": [
        {
            "type": "remotehost",
            "controller-ip": "CONTROLLER_IP",
            "host": "CI_ENDPOINT_HOST",
            "user": "CI_ENDPOINT_USER",
            "userenv": "default",
            "server": "1-2",
            "client": "1-2",
            "config": [
                {
                    "targets": [
                        { "role": "client", "ids": "1" },
                        { "role": "server", "ids": "1" }
                    ],
                    "settings": {
                        "osruntime": "podman"
                    }
                },
                {
                    "targets": [
                        { "role": "client", "ids": "2" },
                        { "role": "server", "ids": "2" }
                    ],
                   "settings": {
                        "osruntime": "chroot"
                    }
                }             
            ]
        },
        {
            "type": "remotehost",
            "controller-ip": "CONTROLLER_IP",
            "host": "CI_ENDPOINT_HOST",
            "user": "CI_ENDPOINT_USER",
            "userenv": "default",
            "profiler": "1",
            "config": [
                {
                    "targets": [
                        { "role": "profiler", "ids": "1" }
                    ],
                    "settings": {
                        "osruntime": "chroot"
                    }
                }
            ]
        }
    ],
    "run-params": {
	    "num-samples": 1,
	    "test-order": "s"
    }
}

=== atheurer/rickshaw/util/crucible-ci/cyclictest.k8s.json
{
    "benchmarks": [
        {
            "name": "cyclictest",
            "ids": "1",
            "mv-params": {
                "global-options": [
                    {
			"name": "required",
			"params": [
                            { "arg": "duration", "vals": [ "10" ], "role": "client" },
                            { "arg": "priority", "vals": [ "1", "2" ], "role": "client" },
                            { "arg": "smi", "vals": [ "off" ], "role": "client" }
			]
                    }
                ],
                "sets": [
                    {
			"include": "required"
                    }
                ]
            }
        }
    ],
    "tool-params": [
        {
            "tool": "sysstat"
        },
        {
            "tool": "procstat"
        }
    ],
    "tags": {
        "description": "cyclictest-k8s-run-file-json"
    },
    "endpoints": [
        {
            "type": "k8s",
            "controller-ip": "CONTROLLER_IP",
            "host": "CI_ENDPOINT_HOST",
            "user": "CI_ENDPOINT_USER",
            "server": 1,
            "client": 1,
            "config": [
                {
                    "targets": [
                        { "role": "client", "ids": "1-2" }
                    ],
                    "settings": {
                        "securityContext": {
			    "privileged": true
                        }
                    }
                },
                {
                    "targets": "all",
                    "settings": {
                        "cpu-partitioning": 1
                    }
                }
            ]
        }
    ],
    "run-params": {
	    "num-samples": 1,
	    "test-order": "s"
    }
}

=== atheurer/rickshaw/util/crucible-ci/iperf.k8s.json
{
    "benchmarks": [
        {
            "name": "iperf",
            "ids": "1-2",
            "mv-params": {
                "global-options": [
                    {
                        "name": "required",
                        "params": [
			    { "arg": "time", "vals": [ "10" ], "role": "client" },
			    { "arg": "protocol", "vals": [ "tcp" ] },
			    { "arg": "bitrate", "vals": [ "0" ] },
			    { "arg": "ifname", "vals" : [ "default-route" ], "role": "server" }
                        ]
                    }
                ],
                "sets": [
                    {
                        "include": "required",
                        "params": [
			    { "arg": "length", "vals": [ "256", "1024" ] }
                        ]
                    }
                ]
            }
        }
    ],
    "tool-params": [
        {
            "tool": "sysstat"
        },
        {
            "tool": "procstat"
        }
    ],
    "tags": {
        "description": "iperf-k8s-run-file-json"
    },
    "endpoints": [
        {
            "type": "k8s",
            "controller-ip": "CONTROLLER_IP",
            "host": "CI_ENDPOINT_HOST",
            "user": "CI_ENDPOINT_USER",
            "server": "1-2",
            "client": "1-2"
        }
    ],
    "run-params": {
	    "num-samples": 1,
	    "test-order": "s"
    }
}

=== atheurer/rickshaw/util/crucible-ci/fio.remotehosts.json
{
    "benchmarks": [
        {
            "name": "fio",
            "ids": "1-2",
            "mv-params": {
                "global-options": [
                    {
			"name": "required",
			"params": [
			    { "arg": "clocksource", "vals": [ "gettimeofday" ] },
			    { "arg": "ramp_time", "vals": [ "5s" ] },

			    { "arg": "bs", "vals": [ "4K", "512K" ] },
			    { "arg": "unlink", "vals": [ "1" ] },
			    { "arg": "filename", "vals": [ "/tmp/fio.foo" ] },
			    { "arg": "runtime", "vals": [ "10s" ] },
			    { "arg": "time_based", "vals": [ "1" ] },
			    { "arg": "norandommap", "vals": [ "ON" ] },
			    { "arg": "rw", "vals": [ "randrw" ] },
			    { "arg": "ioengine", "vals": [ "sync" ] },
			    { "arg": "size", "vals": [ "10M" ] }
			]
                    }
                ],
                "sets": [
                    {
			"include": "required"
                    }
                ]
            }
        }
    ],
    "tool-params": [
        {
            "tool": "sysstat"
        },
        {
            "tool": "procstat"
        }
    ],
    "tags": {
        "description": "fio-remotehosts-run-file-json"
    },
    "endpoints": [
	{
	    "type": "remotehosts",
	    "settings": {
		"user": "CI_ENDPOINT_USER",
		"controller-ip-address": "CONTROLLER_IP"
	    },
	    "remotes": [
		{
		    "engines": [
			{ "role": "client", "ids": [ 1 ] }
		    ],
		    "config": {
			"host": "CI_ENDPOINT_HOST",
			"settings": {
			    "osruntime": "podman"
			}
		    }
		},
		{
		    "engines": [
			{ "role": "client", "ids": [ 2 ] }
		    ],
		    "config": {
			"host": "CI_ENDPOINT_HOST",
			"settings": {
			    "osruntime": "chroot"
			}
		    }
		}
	    ]
	}
    ],
    "run-params": {
	    "num-samples": 1,
	    "test-order": "s"
    }
}

=== atheurer/rickshaw/util/crucible-ci/iperf.remotehosts.json
{
    "benchmarks": [
        {
            "name": "iperf",
            "ids": "1-2",
            "mv-params": {
                "global-options": [
                    {
                        "name": "required",
                        "params": [
			    { "arg": "time", "vals": [ "10" ], "role": "client" },
			    { "arg": "protocol", "vals": [ "tcp" ] },
			    { "arg": "bitrate", "vals": [ "0" ] },
			    { "arg": "ifname", "vals" : [ "default-route" ], "role": "server" }
                        ]
                    }
                ],
                "sets": [
                    {
                        "include": "required",
                        "params": [
			    { "arg": "length", "vals": [ "256", "1024" ] }
                        ]
                    }
                ]
            }
        }
    ],
    "tool-params": [
        {
            "tool": "sysstat"
        },
        {
            "tool": "procstat"
        },
        {
            "tool": "kernel",
            "params": [
                {
                    "arg": "subtools",
                    "val": "turbostat"
                }
            ]
        }
    ],
    "tags": {
        "description": "iperf-remotehosts-run-file-json"
    },
    "endpoints": [
	{
	    "type": "remotehosts",
	    "settings": {
		"user": "CI_ENDPOINT_USER",
		"controller-ip-address": "CONTROLLER_IP"
	    },
	    "remotes": [
		{
		    "engines": [
			{ "role": "client", "ids": [ 1 ] },
			{ "role": "server", "ids": [ 1 ] }
		    ],
		    "config": {
			"host": "CI_ENDPOINT_HOST",
			"settings": {
			    "osruntime": "podman"
			}
		    }
		},
		{
		    "engines": [
			{ "role": "client", "ids": [ 2 ] },
			{ "role": "server", "ids": [ 2 ] }
		    ],
		    "config": {
			"host": "CI_ENDPOINT_HOST",
			"settings": {
			    "osruntime": "chroot"
			}
		    }
		}
	    ]
	}
    ],
    "run-params": {
	    "num-samples": 1,
	    "test-order": "s"
    }
}

=== atheurer/rickshaw/util/crucible-ci/cyclictest.remotehosts.json
{
    "benchmarks": [
        {
            "name": "cyclictest",
            "ids": "1-2",
            "mv-params": {
                "global-options": [
                    {
			"name": "required",
			"params": [
                            { "arg": "duration", "vals": [ "10" ], "role": "client" },
                            { "arg": "priority", "vals": [ "1", "2" ], "role": "client" },
                            { "arg": "smi", "vals": [ "off" ], "role": "client" }
			]
                    }
                ],
                "sets": [
                    {
			"include": "required"
                    }
                ]
            }
        }
    ],
    "tool-params": [
        {
            "tool": "sysstat"
        },
        {
            "tool": "procstat"
        },
        {
            "tool": "kernel",
            "params": [
                {
                    "arg": "subtools",
                    "val": "turbostat"
                }
            ]
        }
    ],
    "tags": {
        "description": "cyclictest-remotehosts-run-file-json"
    },
    "endpoints": [
	{
	    "type": "remotehosts",
	    "settings": {
		"user": "CI_ENDPOINT_USER",
		"controller-ip-address": "CONTROLLER_IP",
		"cpu-partitioning": true
	    },
	    "remotes": [
		{
		    "engines": [
			{ "role": "client", "ids": [ 1 ] },
			{ "role": "server", "ids": [ 1 ] }
		    ],
		    "config": {
			"host": "CI_ENDPOINT_HOST",
			"settings": {
			    "osruntime": "podman"
			}
		    }
		},
		{
		    "engines": [
			{ "role": "client", "ids": [ 2 ] }
		    ],
		    "config": {
			"host": "CI_ENDPOINT_HOST",
			"settings": {
			    "osruntime": "chroot"
			}
		    }
		}
	    ]
	}
    ],
    "run-params": {
	    "num-samples": 1,
	    "test-order": "s"
    }
}

=== atheurer/rickshaw/util/crucible-ci/sleep.kube.json
{
    "benchmarks": [
        {
            "name": "sleep",
            "ids": "1-2",
            "mv-params": {
                "global-options": [
                    {
			"name": "required",
			"params": [
			    { "arg": "seconds", "vals": [ "10" ] }
			]
                    }
                ],
                "sets": [
                    {
			"include": "required"
                    }
                ]
            }
        }
    ],
    "tool-params": [
        {
            "tool": "sysstat"
        },
        {
            "tool": "procstat"
        },
        {
            "tool": "kernel",
            "params": [
                {
                    "arg": "subtools",
                    "val": "turbostat"
                }
            ]
        }
    ],
    "tags": {
        "description": "sleep-kube-run-file-json"
    },
    "endpoints": [
	{
	    "type": "kube",
	    "controller-ip-address": "CONTROLLER_IP",
	    "host": "CI_ENDPOINT_HOST",
	    "user": "CI_ENDPOINT_USER",
	    "engines": {
		"client": "1-2"
	    }
	}
    ],
    "run-params": {
	    "num-samples": 1,
	    "test-order": "s"
    }
}
