=== atheurer/rickshaw/util/JSON/schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "type": "object",
    "properties": {
        "schema": {
            "type": "object",
            "properties": {
                "version": {
                    "type": "string",
                    "enum": [
                        "2023.09.27"
                    ]
                }
            }
        },
        "tags": {
            "type": "object",
            "additionalProperties": {
                "type": "string"
            }
        },
        "endpoints": {
            "type": "array",
            "items": {
                "minItems": 1,
                "type": "object"
            }
        },
        "tool-params": {
            "type": "array",
            "items": {
                "minItems": 0,
                "type": "object"
            }
        },
        "run-params": {
            "type": "object",
	    "properties": {
		"num-samples": {
		    "type": "integer",
		    "minimum": 1
		},
		"max-sample-failures": {
		    "type": "integer",
		    "minimum": 1
		},
		"test-order": {
		    "type": "string",
		    "enum": [
			"s",
			"i",
			"r"
		    ]
		}
	    },
	    "additionalProperties": false,
	    "required": []
        },
        "benchmarks": {
            "type": "array",
            "minItems": 1,
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },  
                    "ids": {
			"$ref": "#/definitions/number-lists"
                    },
                    "mv-params": {
                        "anyOf": [
                            {
                                "type": "array",
                                "items": {
                                    "minItems": 1,
                                    "type": "object"
                                }
                            },
                            {
                                "type": "object"
                            }
                        ]
                    }
                },
                "additionalProperties": false,
                "required": [
                    "name",
                    "ids",
                    "mv-params"
                ]
            }
        }
    },
    "additionalProperties": false,
    "required": [
        "benchmarks"
    ],
    "definitions": {
        "number-lists": {
            "anyOf": [
                {
                    "type": "string",
                    "pattern": "^(([1-9][0-9]*)(-[1-9][0-9]*)?)(\\+(([1-9][0-9]*)(-[1-9][0-9]*)?))*$"
                },
                {
                    "type": "integer"
                },
                {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "anyOf": [
                            {
                                "type": "string",
                                "pattern": "^(([1-9][0-9]*)(-[1-9][0-9]*)?)$"
                            },
                            {
                                "type": "integer"
                            }
                        ]
                    }
                }
            ]
        }
    }
}

=== atheurer/rickshaw/util/crucible-ci/fio.k8s.json
{
    "benchmarks": [
        {
            "name": "fio",
            "ids": "1-2",
            "mv-params": {
                "global-options": [
                    {
			"name": "required",
			"params": [
			    { "arg": "clocksource", "vals": [ "gettimeofday" ] },
			    { "arg": "ramp_time", "vals": [ "5s" ] },

			    { "arg": "bs", "vals": [ "4K", "512K" ] },
			    { "arg": "unlink", "vals": [ "1" ] },
			    { "arg": "filename", "vals": [ "/tmp/fio.foo" ] },
			    { "arg": "runtime", "vals": [ "10s" ] },
			    { "arg": "time_based", "vals": [ "1" ] },
			    { "arg": "norandommap", "vals": [ "ON" ] },
			    { "arg": "rw", "vals": [ "randrw" ] },
			    { "arg": "ioengine", "vals": [ "sync" ] },
			    { "arg": "size", "vals": [ "10M" ] }
			]
                    }
                ],
                "sets": [
                    {
			"include": "required"
                    }
                ]
            }
        }
    ],
    "tool-params": [
        {
            "tool": "sysstat"
        },
        {
            "tool": "procstat"
        },
        {
            "tool": "kernel",
            "params": [
                {
                    "arg": "subtools",
                    "val": "turbostat"
                }
            ]
        }
    ],
    "tags": {
        "description": "fio-k8s-run-file-json"
    },
    "endpoints": [
        {
            "type": "k8s",
            "controller-ip": "CONTROLLER_IP",
            "host": "CI_ENDPOINT_HOST",
            "user": "CI_ENDPOINT_USER",
            "client": "1-2"
        }
    ],
    "run-params": {
	    "num-samples": 1,
	    "test-order": "s"
    }
}

=== atheurer/rickshaw/util/crucible-ci/oslat.remotehost.json
{
    "benchmarks": [
        {
            "name": "oslat",
            "ids": "1",
            "mv-params": {
                "global-options": [
                    {
                        "name": "common-params",
                        "params": [
                            { "arg": "duration", "vals": [ "10" ], "role": "client" },
                            { "arg": "rtprio", "vals": [ "1", "2" ], "role": "client" }
                        ]
                    }
                ],
                "sets": [
                    {
                        "include": "common-params"
                    }
                ]
            }
        }
    ],
    "tool-params": [
        {
            "tool": "sysstat"
        },
        {
            "tool": "procstat"
        }
    ],
    "tags": {
        "description": "oslat-remotehost-run-file-json"
    },
    "endpoints": [
        {
            "type": "remotehost",
            "controller-ip": "CONTROLLER_IP",
            "host": "CI_ENDPOINT_HOST",
            "user": "CI_ENDPOINT_USER",
            "server": "1",
            "client": "1-2",
            "config": [
                {
                    "targets": [
                        { "role": "client", "ids": "1" },
                        { "role": "server", "ids": "1" }
                    ],
                    "settings": {
                        "osruntime": "podman"
                    }
                },
                {
                    "targets": [
                        { "role": "client", "ids": "2" }
                    ],
                   "settings": {
                        "osruntime": "chroot"
                    }
                },
                {
                   "targets": "default",
                   "settings": {
                        "cpu-partitioning": "1"
                    }
                }             
            ]
        },
        {
            "type": "remotehost",
            "controller-ip": "CONTROLLER_IP",
            "host": "CI_ENDPOINT_HOST",
            "user": "CI_ENDPOINT_USER",
            "profiler": "1",
            "config": [
                {
                    "targets": [
                        { "role": "profiler", "ids": "1" }
                    ],
                    "settings": {
                        "osruntime": "podman"
                    }
                }
            ]
        }
    ],
    "run-params": {
	"num-samples": 1,
	"test-order": "s"
    }
}

=== atheurer/rickshaw/util/crucible-ci/uperf.k8s.json
{
    "benchmarks": [
        {
            "name": "uperf",
            "ids": "1-2",
            "mv-params": {
                "global-options": [
                    {
                        "name": "required",
                        "params": [
                            { "arg": "protocol", "vals": [ "tcp" ], "role": "client" },
                            { "arg": "wsize", "vals": [ "64" ], "role": "client" },
                            { "arg": "rsize", "vals": [ "64" ], "role": "client" },
                            { "arg": "duration", "vals": [ "10" ], "role": "client" },
                            { "arg": "ifname", "vals" : [ "default-route" ], "role": "server" }
                        ]
                    }
                ],
                "sets": [
                    {
                        "include": "required",
                        "params": [
                            { "arg": "test-type", "vals": [ "stream" ], "role": "client" },
                            { "arg": "nthreads", "vals": [ "1", "8" ], "role": "client" }
                        ]
                    }
                ]
            }
        }
    ],
    "tool-params": [
        {
            "tool": "sysstat"
        },
        {
            "tool": "procstat"
        }
    ],
    "tags": {
        "description": "uperf-k8s-run-file-json"
    },
    "endpoints": [
        {
            "type": "k8s",
            "controller-ip": "CONTROLLER_IP",
            "host": "CI_ENDPOINT_HOST",
            "user": "CI_ENDPOINT_USER",
            "server": "1-2",
            "client": "1-2"
        }
    ],
    "run-params": {
	    "num-samples": 1,
	    "test-order": "s"
    }
}

=== atheurer/rickshaw/util/crucible-ci/multi.remotehosts.json
{
    "benchmarks": [
        {
            "name": "iperf",
            "ids": "1",
            "mv-params": {
                "global-options": [
                    {
                        "name": "required",
                        "params": [
                            { "arg": "time", "vals": [ "10" ], "role": "client" },
                            { "arg": "protocol", "vals": [ "tcp" ] },
                            { "arg": "bitrate", "vals": [ "0" ] },
                            { "arg": "ifname", "vals" : [ "default-route" ], "role": "server" }
                        ]
                    }
                ],
                "sets": [
                    {
                        "include": "required",
                        "params": [
                            { "arg": "length", "vals": [ "256", "1024" ] }
                        ]
                    }
                ]
            }
        },
        {
            "name": "uperf",
            "ids": "2",
            "mv-params": {
                "global-options": [
                    {
                        "name": "required",
                        "params": [
                            { "arg": "protocol", "vals": [ "tcp" ], "role": "client" },
                            { "arg": "wsize", "vals": [ "64" ], "role": "client" },
                            { "arg": "rsize", "vals": [ "64" ], "role": "client" },
                            { "arg": "duration", "vals": [ "10" ], "role": "client" },
                            { "arg": "ifname", "vals" : [ "default-route" ], "role": "server" }
                        ]
                    }
                ],
                "sets": [
                    {
                        "include": "required",
                        "params": [
                            { "arg": "test-type", "vals": [ "stream" ], "role": "client" },
                            { "arg": "nthreads", "vals": [ "1", "8" ], "role": "client" }
                        ]
                    }
                ]
            }
        }
    ],
    "tool-params": [
        {
            "tool": "sysstat"
        },
        {
            "tool": "procstat"
        }
    ],
    "tags": {
        "description": "mulitbench-remotehosts-run-file-json"
    },
    "endpoints": [
	{
	    "type": "remotehosts",
	    "settings": {
		"user": "CI_ENDPOINT_USER",
		"controller-ip-address": "CONTROLLER_IP"
	    },
	    "remotes": [
		{
		    "engines": [
			{ "role": "client", "ids": [ 1 ] },
			{ "role": "server", "ids": [ 1 ] }
		    ],
		    "config": {
			"host": "CI_ENDPOINT_HOST",
			"settings": {
			    "osruntime": "podman"
			}
		    }
		},
		{
		    "engines": [
			{ "role": "client", "ids": [ 2 ] },
			{ "role": "server", "ids": [ 2 ] }
		    ],
		    "config": {
			"host": "CI_ENDPOINT_HOST",
			"settings": {
			    "osruntime": "chroot"
			}
		    }
		}
	    ]
	}
    ],
    "run-params": {
	    "num-samples": 1,
	    "test-order": "s"
    }
}

=== atheurer/rickshaw/util/crucible-ci/fio.remotehost.json
{
    "benchmarks": [
        {
            "name": "fio",
            "ids": "1",
            "mv-params": {
                "global-options": [
                    {
			"name": "required",
			"params": [
			    { "arg": "clocksource", "vals": [ "gettimeofday" ] },
			    { "arg": "ramp_time", "vals": [ "5s" ] },

			    { "arg": "bs", "vals": [ "4K" ] },
			    { "arg": "unlink", "vals": [ "1" ] },
			    { "arg": "filename", "vals": [ "/tmp/fio.foo" ] },
			    { "arg": "runtime", "vals": [ "10s" ] },
			    { "arg": "time_based", "vals": [ "1" ] },
			    { "arg": "norandommap", "vals": [ "ON" ] },
			    { "arg": "rw", "vals": [ "randrw" ] },
			    { "arg": "ioengine", "vals": [ "sync" ] },
			    { "arg": "size", "vals": [ "10M" ] }
			]
                    }
                ],
                "sets": [
                    {
			"include": "required"
                    }
                ]
            }
        }
    ],
    "tool-params": [
        {
            "tool": "sysstat",
            "params": [
                { "arg": "subtools", "val": "mpstat", "enabled": "yes" }
            ]
        },
        {
            "tool": "procstat"
        }
    ],
    "tags": {
        "run": "fio-run-file-json",
        "userenv": "default"
    },
    "endpoints": [
        {
            "type": "remotehost",
            "controller-ip": "CONTROLLER_IP",
            "host": "CI_ENDPOINT_HOST",
            "user": "CI_ENDPOINT_USER",
            "userenv": "default",
            "client": "1-2",
            "config": [
                {
                    "targets": [
                        { "role": "client", "ids": "1" }
                    ],
                    "settings": {
                        "osruntime": "podman"
                    }
                },
                {
                    "targets": [
                        { "role": "client", "ids": "2" }
                    ],
                   "settings": {
                        "osruntime": "chroot"
                    }
                }             
            ]
        },
        {
            "type": "remotehost",
            "controller-ip": "CONTROLLER_IP",
            "host": "CI_ENDPOINT_HOST",
            "user": "CI_ENDPOINT_USER",
            "userenv": "default",
            "profiler": "1",
            "config": [
                {
                    "targets": [
                        { "role": "profiler", "ids": "1" }
                    ],
		    "settings": {
			"osruntime": "podman"
		    }
                }
            ]
        }
    ],
    "run-params": {
	    "num-samples": 1,
	    "test-order": "s"
    }
}

=== atheurer/rickshaw/util/tests/JSON/input-number-lists.json
{
    "benchmarks": [
	{
	    "name": "iperf",
	    "ids": "1-10+21-30",
	    "mv-params": {
		"global-options": [
		    {
			"name": "required",
			"params": [
			    { "arg": "time", "vals": [ "10" ], "role": "client" },
			    { "arg": "protocol", "vals": [ "tcp" ] },
			    { "arg": "bitrate", "vals": [ "0" ] },
			    { "arg": "ifname", "vals": [ "default-route" ], "role": "server" }
			]
		    }
		],
		"sets": [
		    {
			"include": "required",
			"params": [
			    { "arg": "length", "vals": [ "256" ] }
			]
		    }
		]
	    }
	},
	{
	    "name": "uperf",
	    "ids": [
		"11-20",
		"31-39",
		40
	    ],
	    "mv-params": {
		"global-options": [
		    {
			"name": "required",
			"params": [
			    { "arg": "protocol", "vals": [ "tcp" ], "role": "client" },
			    { "arg": "wsize", "vals": [ "256" ], "role": "client" },
			    { "arg": "rsize", "vals": [ "256" ], "role": "client" },
			    { "arg": "duration", "vals": [ "10" ], "role": "client" },
			    { "arg": "ifname", "vals" : [ "default-route" ], "role": "server" }
			]
		    }
		],
		"sets": [
		    {
			"include": "required",
			"params": [
			    { "arg": "test-type", "vals": [ "stream" ], "role": "client" },
			    { "arg": "nthreads", "vals": [ "1" ], "role": "client" }
			]
		    }
		]
	    }
	}
    ],
    "tags": {
	"foo": "bar"
    },
    "tool-params": [],
    "endpoints": [
	{
	    "type": "k8s",
	    "controller-ip": "K8S_CONTROLLER_IP",
	    "host": "K8S_ENDPOINT_HOST_1",
	    "user": "K8S_ENDPOINT_USER_1",
	    "userenv": "rhubi9",
	    "unique-project": 1,
	    "kubeconfig": 0,
	    "server": "1-10+31-40",
	    "client": [
		"11-20",
		"21-29",
		30
	    ],
	    "config": [
		{
		    "targets": [
			{ "role": "server", "ids": "1-10+31-40" }
		    ],
		    "settings": {
			"nodeSelector": {
                            "kubernetes.io/hostname": "worker-001"
                        }
		    }
		},
		{
		    "targets": [
			{ "role": "client", "ids": [ "11-20", "21-29", 30 ] }
		    ],
		    "settings": {
			"nodeSelector": {
                            "kubernetes.io/hostname": "worker-002"
                        }
		    }
		}
	    ]
	},
	{
	    "type": "k8s",
	    "controller-ip": "K8S_CONTROLLER_IP",
	    "host": "K8S_ENDPOINT_HOST_2",
	    "user": "K8S_ENDPOINT_USER_2",
	    "userenv": "rhubi9",
	    "unique-project": 1,
	    "kubeconfig": 0,
	    "server": [
		11,
		"12-20",
		"21-30"
	    ],
	    "client": "1-10+31-40",
	    "config": [
		{
		    "targets": [
			{ "role": "server", "ids": [ 11, "12-20", "21-30" ] }
		    ],
		    "settings": {
			"nodeSelector": {
                            "kubernetes.io/hostname": "worker-003"
                        }
		    }
		},
		{
		    "targets": [
			{ "role": "client", "ids": "1-10+31-40" }
		    ],
		    "settings": {
			"nodeSelector": {
                            "kubernetes.io/hostname": "worker-004"
                        }
		    }
		}
	    ]
	}
    ],
    "run-params": {
	"num-samples": 1,
	"test-order": "s"
    }
}

=== atheurer/rickshaw/util/crucible-ci/multi.k8s.json
{
    "benchmarks": [
        {
            "name": "iperf",
            "ids": "1",
            "mv-params": {
                "global-options": [
                    {
                        "name": "required",
                        "params": [
                            { "arg": "time", "vals": [ "10" ], "role": "client" },
                            { "arg": "protocol", "vals": [ "tcp" ] },
                            { "arg": "bitrate", "vals": [ "0" ] },
                            { "arg": "ifname", "vals" : [ "default-route" ], "role": "server" }
                        ]
                    }
                ],
                "sets": [
                    {
                        "include": "required",
                        "params": [
                            { "arg": "length", "vals": [ "256", "1024" ] }
                        ]
                    }
                ]
            }
        },
        {
            "name": "uperf",
            "ids": "2",
            "mv-params": {
                "global-options": [
                    {
                        "name": "required",
                        "params": [
                            { "arg": "protocol", "vals": [ "tcp" ], "role": "client" },
                            { "arg": "wsize", "vals": [ "64" ], "role": "client" },
                            { "arg": "rsize", "vals": [ "64" ], "role": "client" },
                            { "arg": "duration", "vals": [ "10" ], "role": "client" },
                            { "arg": "ifname", "vals" : [ "default-route" ], "role": "server" }
                        ]
                    }
                ],
                "sets": [
                    {
                        "include": "required",
                        "params": [
                            { "arg": "test-type", "vals": [ "stream" ], "role": "client" },
                            { "arg": "nthreads", "vals": [ "1", "8" ], "role": "client" }
                        ]
                    }
                ]
            }
        }
    ],
    "tool-params": [
        {
            "tool": "sysstat"
        },
        {
            "tool": "procstat"
        },
        {
            "tool": "kernel",
            "params": [
                {
                    "arg": "subtools",
                    "val": "turbostat"
                }
            ]
        }
    ],
    "tags": {
        "description": "multibench-k8s-run-file-json"
    },
    "endpoints": [
        {
            "type": "k8s",
            "controller-ip": "CONTROLLER_IP",
            "host": "CI_ENDPOINT_HOST",
            "user": "CI_ENDPOINT_USER",
            "server": "1-2",
            "client": "1-2"
        }
    ],
    "run-params": {
	    "num-samples": 1,
	    "test-order": "s"
    }
}

=== atheurer/rickshaw/util/crucible-ci/sleep.k8s.json
{
    "benchmarks": [
        {
            "name": "sleep",
            "ids": "1-2",
            "mv-params": {
                "global-options": [
                    {
			"name": "required",
			"params": [
			    { "arg": "seconds", "vals": [ "10" ] }
			]
                    }
                ],
                "sets": [
                    {
			"include": "required"
                    }
                ]
            }
        }
    ],
    "tool-params": [
        {
            "tool": "sysstat"
        },
        {
            "tool": "procstat"
        },
        {
            "tool": "kernel",
            "params": [
                {
                    "arg": "subtools",
                    "val": "turbostat"
                }
            ]
        }
    ],
    "tags": {
        "description": "sleep-k8s-run-file-json"
    },
    "endpoints": [
        {
            "type": "k8s",
            "controller-ip": "CONTROLLER_IP",
            "host": "CI_ENDPOINT_HOST",
            "user": "CI_ENDPOINT_USER",
            "client": "1-2"
        }
    ],
    "run-params": {
	    "num-samples": 1,
	    "test-order": "s"
    }
}
